### ISSUE TITLE
Themeing a wp-maintenance mode template from within my child theme

### ISSUE THREAD

**Issue by solaceten** [Codeinwp/wp-maintenance-mode#332] opened 2022-10-04 01:53 UTC
Hi team

Previously, I have written some code to allow me to use my own maintenance mode landing theme page, but have it inside my theme directory.  In the child theme directory I had:

wp-content
- themes
- - my child theme
- - -  wp-maintenance-mode.php
- - -  wp-maintenance-mode.css

But with a recent update, these are now broken.  Although they still load, the website shows underneath them on the website landing page.

So - if we want to customise a theme, and use it from inside our child theme, what is the best way to do that now ?

Is this still the recommended method:

https://wordpress.org/support/topic/feature-request-allow-overriding-templates/#post-12025524

Thank you

**Comment by solaceten** [comment] 2022-10-05 01:50
Hi again

OK well scrub the above !! I found the answer inside maintenance.php file:  Looks like my previous method has been deprecated.....

* This template can be overridden by copying it to one of these paths:
 * - /wp-content/themes/{your_child_theme}/wp-maintenance-mode/maintenance.php
 * - /wp-content/themes/{your_theme}/wp-maintenance-mode/maintenance.php
 * - /wp-content/themes/{your_child_theme}/wp-maintenance-mode.php [deprecated]
 * - /wp-content/themes/{your_theme}/wp-maintenance-mode.php [deprecated]
 * - /wp-content/wp-maintenance-mode.php

**Comment by selul** [comment] 2022-11-24 08:38
@solaceten my understanding when you closed this was it is working fine. 

We have a PR ready here #333, feel free to download the zip here and let us know if it works. https://github.com/Codeinwp/wp-maintenance-mode/pull/333#issuecomment-1266932296

**Comment by arinaturcu** [comment] 2023-02-06 09:47
Hi, @solaceten!

What I understand is that your child theme template loads fine, but the problem is that the notice `Action required: you don't have a page as Maintenance page.` is still showing up, is this right?

**Comment by arinaturcu** [comment] 2023-02-09 15:41
@solaceten Thank you!

Here is a PR that solves the issue: https://github.com/Codeinwp/wp-maintenance-mode/pull/365
Feel free to download the build and check if everything is fine.

**Closed** 2023-03-31 10:29 UTC
Labels: bug, released
