### ISSUE TITLE
Templates page look unusable on tastewp

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-maintenance-mode#390] opened 2023-06-05 11:05 UTC
### Description

Tried to take a look at Lightstart and here is what the templates page looks like: https://vertis.d.pr/i/J8kOhu.

### Step-by-step reproduction instructions

1. Go to the design tab
2. https://vertis.d.pr/i/J8kOhu

### Environment info

https://pastebin.com/crkpgiFf

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment] 2023-06-06 07:58
This happens using **Safari** browser, it looks fine with Chrome or Firefox.

**Comment by irinelenache** [comment] 2023-11-09 09:30
@girishpanchal30 Tested and the issue is fixed now 👍

**Closed** 2023-12-22 15:17 UTC
Labels: bug, released
